export const colorHexes: Record<string, string> = {
    white: "#ffffff",
    orange: "#f9801d",
    magenta: "#c74ebd",
    light_blue: "#3ab3da",
    yellow: "#fed83d",
    lime: "#80c71f",
    pink: "#f38baa",
    gray: "#474f52",
    light_gray: "#9d9d97",
    cyan: "#169c9c",
    purple: "#8932b8",
    blue: "#3c44aa",
    brown: "#835432",
    green: "#5e7c16",
    red: "#b02e26",
    black: "#1e1b1b"
};

export const patternList: string[] = [
    'border',
    'bricks',
    'circle',
    'creeper',
    'cross',
    'curly_border',
    'diagonal_left',
    'diagonal_right',
    'diagonal_up_left',
    'diagonal_up_right',
    'flow',
    'flower',
    'globe',
    'gradient_up',
    'gradient',
    'guster',
    'half_horizontal_bottom',
    'half_horizontal',
    'half_vertical_right',
    'half_vertical',
    'mojang',
    'piglin',
    'rhombus',
    'skull',
    'small_stripes',
    'square_bottom_left',
    'square_bottom_right',
    'straight_cross',
    'stripe_bottom',
    'stripe_center',
    'stripe_downleft',
    'stripe_downright',
    'stripe_left',
    'stripe_middle',
    'stripe_right',
    'stripe_top',
    'triangle_bottom',
    'triangle_top',
    'triangles_bottom',
    'triangles_top', // TODO: MISSING SOME SQUARES?? CHECK IMAGES
] as const;